spring.jpa:
  hibernate.ddl-auto: ""
spring:
  jpa:
    show-sql: true
logging:
  level:
    org.springframework: INFO
    com.mkyong: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log